### ISSUE TITLE
intermittent segfault (when casting NULL MAP_KEYS()?)

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb#11117]
### What happens?

I'm not sure the exact root cause of this, but I encountered it when trying workarounds for #11116, so possibly related.

I am on
2021 Macbook
M1 Max
64GB
MacOS 14.1.1

This seems to affect different platforms totally chaotically?
- never segfaults on the `v0.10.0` CLI binary from homebrew
- sometimes (~20% of the time?) segfaults using `0.10.0` via the python bindings
- sometimes (~20% of the time?) segaults using `v0.9.2` vscode extension from https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.duckdb-sql-tools (which I assume is nodejs??)

Here is the SQL (I tried simplifying, but could possible get simplified more)

```sql
SELECT
  MAP(
    CASE
      WHEN NULL::MAP(TEXT, BIGINT) IS NULL
      THEN NULL::TEXT[]
      ELSE MAP_KEYS(NULL::MAP(TEXT, BIGINT))
    END,
    LIST_APPLY(
      MAP_VALUES(NULL::MAP(TEXT, BIGINT))::DOUBLE[],
      __ibis_param_x__ -> __ibis_param_x__ / 34
    )
  );
```

### To Reproduce

for python:

```python
import duckdb

print(duckdb.__version__)
# 0.10.0

sql = """
SELECT
  MAP(
    CASE
      WHEN NULL::MAP(TEXT, BIGINT) IS NULL
      THEN NULL::TEXT[]
      ELSE MAP_KEYS(NULL::MAP(TEXT, BIGINT))
    END,
    LIST_APPLY(
      MAP_VALUES(NULL::MAP(TEXT, BIGINT))::DOUBLE[],
      __ibis_param_x__ -> __ibis_param_x__ / 34
    )
  );
"""

conn = duckdb.connect(":memory:")
for i in range(1000):
    print(conn.sql(sql))
```

### OS:

shell.duckdb.org

### DuckDB Version:

0.10.0

### DuckDB Client:

@duckdb/duckdb-wasm@1.28.1-dev166.0

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello @NickCrews, so far I am unable to reproduce this issue using the web shell/CLI using DuckDB 0.10.0. I also run this on a MBP with 64GB RAM and an M1Max CPU but I run macOS 14.4.

**Comment by carlopi** [comment]
shell.duckdb.org works sort of correctly up to the point where the empty map needs to be rendered, and there the shell code (not the duckdb-code) ducks up and renders empty result. This is not a problem in the core library, that looks to me consistent to duckdb CLI. Sorry for the poor experience, to be improved on.

(this is a demo of this rendering more appropriately, at least duckdb side: https://shell.duckdb.org/#queries=v0,SELECT%0A--MAP(%0A----CASE%0A------WHEN-NULL%3A%3AMAP(TEXT%2C-BIGINT)-IS-NULL%0A------THEN-NULL%3A%3ATEXT%5B%5D%0A------ELSE-MAP_KEYS(NULL%3A%3AMAP(TEXT%2C-BIGINT))%0A----END%2C%0A----LIST_APPLY(%0A------MAP_VALUES(NULL%3A%3AMAP(TEXT%2C-BIGINT))%3A%3ADOUBLE%5B%5D%2C%0A------__ibis_param_x__-%20%3E-__ibis_param_x__-%2F-34%0A----)%0A--)%3A%3AVARCHAR-AS-res~)

**Comment by NickCrews** [comment]
Ah yes I just discovered the shell.duckdb.org rendering bug, bug filed at https://github.com/duckdb/duckdb-wasm/issues/1671. I am editing my original post to be correct here.

I still am getting intermittent segfaults in those other environments. But now it appears that all the segfauliting environments us duckdb<0.10.0, so maybe it is fixed in 0.10.0. Let me upgrade to that and test more.

**Comment by NickCrews** [comment]
OK it DOES still sometimes segfault on 0.10.0 with python bindings. See the repro snippet I added to the original post.

**Comment by szarnyasg** [comment]
Hello @NickCrews, thanks for your efforts! Unfortunately, this still doesn't reproduce on my machine. I tried both Python 3.11 and 3.12. Strange.

**Comment by NickCrews** [comment]
hmmm, wheee it looks like it's time for a 🐰 🕳️ !

I tried again from scratch with a minimal environment, and still am getting the segfault:
```bash
mkdir test
cd test
python -m venv .venv
. .venv/bin/activate
python -m pip install duckdb==0.1.0
python test.py
```
I am using
- wheel `cp311-cp311-macosx_11_0_arm64`
- `Python 3.11.6 (main, Oct 23 2023, 09:04:08) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin`

Other ideas on what environment info I should look up? Is there a way to turn on debugging so I can post the exact cause of the segfault? Or some other debugging I can do on my machine if you can't repro?

**Comment by Tishj** [comment]
It would be great if you could check with the latest nightly build, that way we can rule out if it's already been fixed on `main`

**Comment by Tishj** [comment]
Running your provided `test.py` on both python 3.9 and 3.11 with the latest build does not produce an error for me

**Comment by cmdlineluser** [comment]
I have an older macbook that produces the segfault on `0.10.0` (Python 3.10)

I have not been able to replicate it with any of the dev wheels. (earliest `0.10.1-dev845`)

**Comment by hannes** [comment]
Managed to reproduce this on my Mac using duckdb 0.10.0 from pip and with Python 3.12 - does not always crash

**Comment by hannes** [comment]
I cannot reproduce this with a development build of DuckDB for Python, can you try installing the latest prerelease with `pip install duckdb --pre --upgrade --force` and see if it still reproduces? It might be already fixed.

**Comment by NickCrews** [comment]
nice, with that prerelease `duckdb-0.10.1.dev1206` I cannot repro this. Thanks!

Do we still want to add a test case for this?
