### ISSUE TITLE
Julia client doesn't always return a complete `QueryResult`

### ISSUE THREAD

**Issue by suvayu** [duckdb/duckdb#11196]
__UPDATE:__ with 0.10.0 converting to `DataFrame` also failed similarly, but with 0.10.1 conversion to `DataFrame` works, although I get the same error when trying to use the `QueryResult` directly. I updated the MWE appropriately.

---

### What happens?

Sometimes when running a query from Julia, I get an incomplete `QueryResult` object. In these cases adding something in the next line, say a `@printf` or `@show` makes the problem go away.

If I understand it correctly, the Julia client doesn't wait for DuckDB to return.  So if DuckDB takes longer than it takes Julia to reach a part of the code where the results are used, Julia finds `missing` and fails.

I have two questions:
- I noticed that this is happening even for very simple queries (like in the MWE), which makes me wonder why/where the slow down is?
- Is there something in the API that I can use to say "wait for the results before returning"?  That would allow me to move on with development, and come back to investigate later.

PS: I'm aware of the Julia client's status as "unsupported", so I'm looking for pointers so that I can resolve the issue myself.

### To Reproduce (updated)

```julia
import DuckDB as DD
using DataFrames: DataFrame

function check_tbl(con::DD.DB, source::String)
    df = DD.DBInterface.execute(con, "SHOW TABLES") |> DataFrame
    tbls = df[!, :name]
    source in tbls
end

con = DD.DBInterface.connect(DD.DB)
DD.DBInterface.execute(con, "CREATE TABLE mytbl AS SELECT * FROM range(5)")
@show check_tbl(con, "mytbl")

DD.DBInterface.execute(con, "DROP TABLE mytbl")
@show check_tbl(con, "mytbl")

function check_tbl_bad(con::DD.DB, source::String)
    res = DD.DBInterface.execute(con, "SHOW TABLES")
    # @show res
    tbls = res.tbl[:name]
    source in tbls
end

con = DD.DBInterface.connect(DD.DB)
DD.DBInterface.execute(con, "CREATE TABLE mytbl AS SELECT * FROM range(5)")
@show check_tbl_bad(con, "mytbl")

DD.DBInterface.execute(con, "DROP TABLE mytbl")
@show check_tbl_bad(con, "mytbl")
```

This gives me the following crash:
```
check_tbl(con, "mytbl") = true
check_tbl(con, "mytbl") = false
ERROR: LoadError: MethodError: no method matching getindex(::Missing, ::Symbol)
Stacktrace:
 [1] check_tbl_bad(con::DuckDB.DB, source::String)
   @ Main /path/to/mwe.jl:20
 [2] top-level scope
   @ show.jl:1128
in expression starting at /path/to/mwe.jl:12
```

However if I uncomment the `@show res` line, I get the expected behaviour:
```
check_tbl(con, "mytbl") = true
check_tbl(con, "mytbl") = false
res = (name = Union{Missing, String}["mytbl"],)
check_tbl_bad(con, "mytbl") = true
res = (name = String[],)
check_tbl_bad(con, "mytbl") = false
```

### OS:

Fedora 39 (but my colleagues also saw it on Windows 11)

### DuckDB Version:

v0.10.1

### DuckDB Client:

Julia 1.9.2 

### Full Name:

Suvayu

### Affiliation:

NL eScience Center

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I don't think what you're seeing is an "incomplete" QueryResult, I think what you're seeing is a StreamQueryResult as opposed to a MaterializedQueryResult

It could be that the julia result conversion code is attempting to call a method that the stream query result can't handle (because it's streaming, not the whole result is materialized so requesting a row index is likely not going to work)

I believe `execute` is expected to create a materialized query result by default though, so something might be up there?
Instead of letting the result conversion code fail, instead it could likely be solved by calling Materialize on the StreamQueryResult instead.

**Comment by suvayu** [comment]
Thanks a lot! That gives me a lot to work with :)  I'll report back with my findings

**Comment by Tishj** [comment]
Though actually looking at the code, I can't see any definition for `getindex`, so it sounds like it's just broken?

**Comment by suvayu** [comment]
Thanks for your comments.  My original use was actually to make a `DataFrame` from the result, that's where I noticed the issue.  I tried your suggestion to collect with my MWE like this:

```julia
res, = DD.DBInterface.executemultiple(con, "SHOW TABLES") |> collect
```

Unfortunately that doesn't resolve the issue.  I have some time this week, I'll investigate some more.

**Comment by suvayu** [comment]
Okay, I updated to the latest patch release 0.10.1 and now it works partially.

```julia
df = DD.DBInterface.execute(con, "SHOW TABLES") |> DataFrame  # works
res = DD.DBInterface.execute(con, "SHOW TABLES")                           # same as before
```

I'll update the OP and the MWE to reflect this.  Since conversion to DataFrame is working, it's an acceptable workaround for now.

**Comment by suvayu** [comment]
Okay thanks, I didn't realise this difference between `execute` and `query`.  I'll keep this in mind.  You may consider this resolved by the 0.10.1 release.
