### ISSUE TITLE
Extension loading fails with a 403 error.

### ISSUE THREAD

**Issue by ju-klein** [duckdb/duckdb#19065]
### What happens?

(Copied from another bug report by myself.)
When loading extensions, DuckDB looks at an URL similar to this: [http://extensions.duckdb.org/fd1b726c1c/linux_amd64/json.duckdb_extension.gz](http://extensions.duckdb.org/e1369bc162/linux_amd64/json.duckdb_extension.gz) where e1369bc162 is the hash of a commit. If that commit does not exist, the URL leads to a dead end. This leads to the extension not being able to be downloaded and throwing a 403 instead. Other people seem to have a similar problem (see here https://github.com/duckdb/duckdb-postgres/issues/306) , this might be the root cause.

I could also provide a Dockerfile for my dev environment (or any other information)if you guys need it. 

### To Reproduce

1. cd /DuckDB/src
2. touch random_changed_file.txt
3. git add random_changed_file.txt
4. git commit -m "added awesome additions"
5. git log (observe that the commit hash on main has changed)
6. make all
7. cd ./build/release
8. ./duckdb
9. INSTALL JSON;
10. LOAD JSON;

### OS:

Debian trixie

### DuckDB Version:

DuckDB v1.4.0-dev645 (Development Version) ed9cb375c5, also DuckDB v1.3.1-dev642 (Development Version) fd1b726c1c

### DuckDB Client:

CMD

### Full Name:

Julian Klein

### Affiliation:

MPI-SWS, SIC

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by Tmonster** [comment]
Seems like you are building DuckDB yourself? If so, you can build the JSON extension along with it, and then DuckDB will not look for it at the URL. 

```
GEN=ninja BUILD_EXTENSIONS="json" make
```

should fix the issue

**Comment by ju-klein** [comment]
Hi @Tmonster ,
thank you very much for your suggestion! I did try that indeed and while that _does_ install the JSON extension just fine, it merely circumvents the (potentially) faulty behavior of DuckDB not downloading extensions. So I guess the problem still stands. (Except if I am the only one experiencing this. o0)

**Comment by carlopi** [comment]
DuckDB extensions are known to be at there (this is a hard requirement, and a blocker for releases) for released versions of duckdb (that is, a 'random' commit that has a tag such as `v1.4.0` on duckdb/duckdb, we consider those tags immutable)

DuckDB extensions might be there on other commits if published by the daily process that test and packages nightly builds for duckdb. Those are not guaranteed to be there in eternity, we clean them up from time to time, and a given build might fail. The list of available commits is currently exposed indirectly if you were to check the list of successful builds at https://github.com/duckdb/duckdb/actions/workflows/InvokeCI.yml?query=is%3Asuccess.

DuckDB extensions on commits that are NOT release and that have not been selected for a nightly build that succeeded (and has not been cleaned up afterwards) you could build yourself on need, either locally or on a fork mimicking our workflows. Those should return at the moment a 404 on extensions.duckdb.org.

I am not sure what's actionable, if you have some service that expect a given arbitrary commit to be available, please reach out. In general users are encouraged to use nightly builds to give early feedback / check on old or new bugs, but we generally reccomend to bump to the latest release version, and if that's not feasible for some reason, that would also be welcome feedback.

I will try to find a place in the docs where to insert those informations, this might be better suited as a documentation issue.

@ju-klein: does this solves this, is there information that would be handy that is missing?

**Comment by ju-klein** [comment]
@carlopi Hi Carlo,
many thanks for the information, that does help me indeed quite a bit!
This clears up my confusion and I think I know what my problem is:
I was on main the whole time, I was never on a tagged commit!
The way I understand you ( and please correct me if I'm wrong), I should be on a tagged commit (v1.somethingsomething) and that should enable me to download the extensions. I did just verify that indeed, when I check out `v1.4.1`, I can just `INSTALL JSON` and `LOAD JSON` and everything works.
I am not sure anymore if I saw this in the docs (sorry, when I started on this was too long ago). If not, adding your explanation might help. I am sure it would have helped me. I think this can be closed now.

I am very sorry about the long period until getting back to you, was not intentional!

Best,
Julian

Edit: HOWEVER (sorry!): What is with people who want  to work on DuckDB? They will have local commits with a different hash, so they would still need to get the extensions in a different place, OR branch from a tagged commit and get the extensions first, no? I could imagine that  that MIGHT lead to confusion/problems, no?
