### ISSUE TITLE
JVM SIGSEGV crash

### ISSUE THREAD

**Issue by ricardoekm** [duckdb/duckdb#7596]
### What happens?

The JVM crashes when trying to query a non-existing S3 file. The issue doesn't happen depending on the OS/JVM.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f352beab602, pid=1, tid=127
#
# JRE version: OpenJDK Runtime Environment (17.0.2+8) (build 17.0.2+8-86)
# Java VM: OpenJDK 64-Bit Server VM (17.0.2+8-86, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x25602]  abort+0x1ee
#
# Core dump will be written. Default location: //core.1
#
# The JFR repository may contain useful JFR files. Location: /tmp/2023_05_19_21_20_26_1
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
[thread 129 also had an error]
[thread 72 also had an error]
```
### 

### To Reproduce

```java
var connection = DriverManager.getConnection(getJdbcUrl());
var statement = connection.createStatement();
statement.execute("INSTALL httpfs;LOAD httpfs;SET s3_access_key_id='acces_key';SET s3_secret_access_key='secret';SET s3_region='us-east-1';");
statement.execute("CREATE OR REPLACE TEMP TABLE my_table AS SELECT * FROM 's3://bucket/not_found.json'");
```

### OS:

Docker image openjdk:17-jdk-slim on AmazonLinux2 ami (k8s: 1.23.9, docker: 20.10.17-1.amzn2, containerd: 1.6.6-1.amzn2)

### DuckDB Version:

-

### DuckDB Client:

Java JDBC 0.8.0

### Full Name:

Ricardo Mayerhofer

### Affiliation:

Hopara

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Can you please double check you are using 0.8.0? We fixed an issue very similar to this one recently

**Comment by shreyasGit** [comment]
i am getting this error too #
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000648b56, pid=1, tid=135
#
# JRE version: OpenJDK Runtime Environment Zulu13.54+17-CA (13.0.14+5) (build 13.0.14+5-MTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu13.54+17-CA (13.0.14+5-MTS, mixed mode, sharing, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# C  0x0000000000648b56
#
# Core dump will be written. Default location: /install/citng/service/core.1
#
# An error report file with more information is saved as:
# /install/citng/service/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bu

**Comment by Mause** [comment]
@shreyasGit which version of DuckDB are you using?

**Comment by shreyasGit** [comment]
i am using 0.8.1 the latest as of now, just to give some context , earlier i had issues with glibc on alpine, so installed it in my dockerfile - java.lang.UnsatisfiedLinkError: /tmp/libduckdb_java4480084372361105472.so: Error loading shared library ld-linux-x86-64.so.2:
now i get this above error. works on my windows machine fine, issues in a container

**Comment by Mause** [comment]
@shreyasGit Can you please open a new issue with reproduction information?

**Comment by Mause** [comment]
Closing this one as we're fairly certain this issue is solved

**Comment by shreyasGit** [comment]
ok any pointers what could be causing this on my side?

**Comment by Mause** [comment]
> ok any pointers what could be causing this on my side?

If you open a new issue with full reproduction information I'd be happy to look into it

**Comment by ricardoekm** [comment]
Hi @Mause,
Thanks for the reply. The issue still persists on the latest JDBC driver.

```
implementation group: 'org.duckdb', name: 'duckdb_jdbc', version: '0.8.1'
```

Steps to reproduce:
```java
var connection = DriverManager.getConnection("jdbc:duckdb:");
System.out.println("Product name " + connection.getMetaData().getDatabaseProductName());
System.out.println("Major version " + connection.getMetaData().getJDBCMajorVersion());
System.out.println("Minor version " + connection.getMetaData().getJDBCMajorVersion());
		
var statement = connection.createStatement();
statement.execute("INSTALL httpfs;LOAD httpfs;SET s3_access_key_id='"+ accessKey + "';SET s3_secret_access_key='" + accessSecret + "';SET s3_region='us-east-1';");
statement.execute("CREATE OR REPLACE TEMP TABLE my_table AS SELECT * FROM 's3://bucket/not_found.json'");
```

Also it would be nice if Duck implements the getJDBCMajorVersion and getJDBCMajorVersion methods. Currently it returns 1.

```
Product name DuckDB
Major version 1
Minor version 1
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff67c505602, pid=1, tid=479
#
# JRE version: OpenJDK Runtime Environment (17.0.2+8) (build 17.0.2+8-86)
# Java VM: OpenJDK 64-Bit Server VM (17.0.2+8-86, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x25602]  abort+0x1ee
#
# Core dump will be written. Default location: //core.1
#
# The JFR repository may contain useful JFR files. Location: /tmp/2023_06_26_14_02_35_1
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by ricardoekm** [comment]
Hi @Mause ,
Just checking if we should reopen this issue.

**Comment by solita-kattelus** [comment]
Seems that I'm seeing something that looks similar with AWS lambda container when trying to access non existent s3 file. 

In lambda logs it shows just: 
RequestId: 5e303be7-633b-474e-9767-295af4aa0d71 Error: Runtime exited with error: signal: aborted
Runtime.ExitError

And lambda run dies.

Any idea what might cause this/how to fix it?

**Comment by Mause** [comment]
This was likely fixed by https://github.com/duckdb/duckdb/pull/8685, if one of you could confirm with the latest dev version that would be great

**Comment by carlopi** [comment]
@ricardoekm & @solita-kattelus: We just solved an issue related to non-existent files causing DuckDB to terminate, see for example here: https://github.com/duckdb/duckdb/issues/9340.

Could you update to v0.9.1, force a refresh of the httpfs extension (`FORCE INSTALL httpfs`), and try again? I expect this problem to be solved by the newer httpfs extension.

**Comment by Mytherin** [comment]
Seems to be fixed
