### ISSUE TITLE
Failed to download extension "httpfs" at …/linux_arm64_gcc4/…

### ISSUE THREAD

**Issue by tadpol** [duckdb/duckdb#8035]
### What happens?

python-duckdb fails to download extensions 

> HTTP Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/v0.8.1/linux_arm64_gcc4/httpfs.duckdb_extension.gz"

### To Reproduce

Inside a docker container (I'm using python:3.11-slim) for arm64.

- `docker run -it --rm python:3.11-slim /bin/bash`
- `pip install duckdb`
- `python`
- `import duckdb`
- `duckdb.query("install 'httpfs';")`

It seems like it is looking for extensions in `linux_arm64_gcc4` and those don't exist.  I tried grabbing the ones at `linux_arm64` and putting them in the `~/.duckdb/extensions/v0.8.1/linux_arm64_gcc4/` directory, but they fail to load.

### OS:

docker on macOS on aarch64 

### DuckDB Version:

0.8.1

### DuckDB Client:

python

### Full Name:

michael conrad tadpol tilstra

### Affiliation:

Exosite

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
While I look into this, you can download the extension binaries from this action job instead: https://github.com/duckdb/duckdb/actions/runs/5253133577

**Comment by Mause** [comment]
Okay, this might just be user error actually - the httpfs is built-in to the python package:

```
In [3]: duckdb.sql('from duckdb_extensions()')
Out[3]: 
┌──────────────────┬─────────┬───────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────┬───────────────────┐
│  extension_name  │ loaded  │ installed │ install_path │                                    description                                     │      aliases      │
│     varchar      │ boolean │  boolean  │   varchar    │                                      varchar                                       │     varchar[]     │
├──────────────────┼─────────┼───────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────┼───────────────────┤
│ autocomplete     │ false   │ false     │              │ Add supports for autocomplete in the shell                                         │ []                │
│ excel            │ true    │ NULL      │              │                                                                                    │ []                │
│ fts              │ true    │ true      │ (BUILT-IN)   │ Adds support for Full-Text Search Indexes                                          │ []                │
│ httpfs           │ true    │ true      │ (BUILT-IN)   │ Adds support for reading and writing files over a HTTP(S) connection               │ [http, https, s3] │
│ icu              │ true    │ true      │ (BUILT-IN)   │ Adds support for time zones and collations using the ICU library                   │ []                │
│ inet             │ false   │ false     │              │ Adds support for IP-related data types and functions                               │ []                │
│ jemalloc         │ true    │ true      │ (BUILT-IN)   │ Overwrites system allocator with JEMalloc                                          │ []                │
│ json             │ true    │ true      │ (BUILT-IN)   │ Adds support for JSON operations                                                   │ []                │
│ motherduck       │ false   │ false     │              │ Enables motherduck integration with the system                                     │ [md]              │
│ parquet          │ true    │ true      │ (BUILT-IN)   │ Adds support for reading and writing parquet files                                 │ []                │
│ postgres_scanner │ false   │ false     │              │ Adds support for reading from a Postgres database                                  │ [postgres]        │
│ spatial          │ false   │ false     │              │ Geospatial extension that adds support for working with spatial data and functions │ []                │
│ sqlite_scanner   │ false   │ false     │              │ Adds support for reading SQLite database files                                     │ [sqlite, sqlite3] │
│ tpcds            │ true    │ true      │ (BUILT-IN)   │ Adds TPC-DS data generation and query support                                      │ []                │
│ tpch             │ true    │ true      │ (BUILT-IN)   │ Adds TPC-H data generation and query support                                       │ []                │
│ visualizer       │ true    │ NULL      │              │                                                                                    │ []                │
├──────────────────┴─────────┴───────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────┴───────────────────┤
│ 16 rows                                                                                                                                              6 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by tadpol** [comment]
Thanks for you time.  Little embarrassed I didn't think to check that.

**Comment by tadpol** [comment]
ugh. there is something weird going on.  At my prior comment, I setup a docker container as before and ran the sql to list extensions. I saw that `httpfs` was included, and added my comment.  I then went and updated my Dockerfile for not needed to download `httpfs` and it failed.  I have now rebuilt a container and loaded duckdb multiple times and the extension list shows `httpfs` as not included.

I wonder if there is somehow two versions of 0.8.1 in the caches? Or something else? (still not discounting user error…)

```>>> duckdb.sql('PRAGMA version;')
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ 0.8.1           │ 6536a77232 │
└─────────────────┴────────────┘

>>> duckdb.sql('from duckdb_extensions()')
┌──────────────────┬─────────┬───────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────┬───────────────────┐
│  extension_name  │ loaded  │ installed │ install_path │                                    description                                     │      aliases      │
│     varchar      │ boolean │  boolean  │   varchar    │                                      varchar                                       │     varchar[]     │
├──────────────────┼─────────┼───────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────┼───────────────────┤
│ autocomplete     │ false   │ false     │              │ Add supports for autocomplete in the shell                                         │ []                │
│ fts              │ true    │ true      │ (BUILT-IN)   │ Adds support for Full-Text Search Indexes                                          │ []                │
│ httpfs           │ false   │ false     │              │ Adds support for reading and writing files over a HTTP(S) connection               │ [http, https, s3] │
│ icu              │ true    │ true      │ (BUILT-IN)   │ Adds support for time zones and collations using the ICU library                   │ []                │
│ inet             │ false   │ false     │              │ Adds support for IP-related data types and functions                               │ []                │
│ jemalloc         │ true    │ true      │ (BUILT-IN)   │ Overwrites system allocator with JEMalloc                                          │ []                │
│ json             │ true    │ true      │ (BUILT-IN)   │ Adds support for JSON operations                                                   │ []                │
│ motherduck       │ false   │ false     │              │ Enables motherduck integration with the system                                     │ [md]              │
│ parquet          │ true    │ true      │ (BUILT-IN)   │ Adds support for reading and writing parquet files                                 │ []                │
│ postgres_scanner │ false   │ false     │              │ Adds support for reading from a Postgres database                                  │ [postgres]        │
│ spatial          │ false   │ false     │              │ Geospatial extension that adds support for working with spatial data and functions │ []                │
│ sqlite_scanner   │ false   │ false     │              │ Adds support for reading SQLite database files                                     │ [sqlite, sqlite3] │
│ tpcds            │ true    │ true      │ (BUILT-IN)   │ Adds TPC-DS data generation and query support                                      │ []                │
│ tpch             │ true    │ true      │ (BUILT-IN)   │ Adds TPC-H data generation and query support                                       │ []                │
├──────────────────┴─────────┴───────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────┴───────────────────┤
│ 14 rows                                                                                                                                              6 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘```

**Comment by Mause** [comment]
Okay, this is a bit more involved then. I missed the part we're you're running on *arm64*, not *amd64*, oops

We only just added linux aarch64 wheel builds in the 0.8.1 patch release, so they haven't really been tested out yet, and it looks like might be some issues here

**Comment by martelli** [comment]
Hey! Any news on this issue? This should affect many people using containers on their Apple silicon Macs.
I might try to help if given some pointers.

Thanks!

**Comment by Mause** [comment]
Looking into this further (now that I'm back from holidays), looks like there was some user error on my part. The results I pasted in my earlier comment were from my local dev build, which I had enabled the httpfs extension as part of. It isn't actually built into any of the Python versions that I can see

What this actually means is that we need to update the DuckDB Python extensions job to build for linux_arm64 as well as amd64

**Comment by Rudi79** [comment]
I guess the same holds true for the Julia extension. (latest version)
It fails with 
`Execute of query "INSTALL httpfs" failed: HTTP Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/v0.8.1/windows_amd64_mingw/httpfs.duckdb_extension.gz"
Extension "httpfs" is an existing extension.`
Trying do download the file manualy leads to
`RequestError: HTTP/1.1 403 Forbidden while requesting https://extensions.duckdb.org/v0.8.1/windows_amd64_mingw/httpfs.duckdb_extension.gz`

**Comment by Mause** [comment]
> I guess the same holds true for the Julia extension. (latest version) It fails with `Execute of query "INSTALL httpfs" failed: HTTP Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/v0.8.1/windows_amd64_mingw/httpfs.duckdb_extension.gz" Extension "httpfs" is an existing extension.` Trying do download the file manualy leads to `RequestError: HTTP/1.1 403 Forbidden while requesting https://extensions.duckdb.org/v0.8.1/windows_amd64_mingw/httpfs.duckdb_extension.gz`

This one is a bit different, and is somewhat intentional. Julia on Windows uses mingw to compile, which means we have to compile a different copy of all the extensions using that toolchain, which hasn't yet been done

**Comment by matthewmturner** [comment]
hi there, having issues with this as well - prevents me from using duckdb on arm64 ubuntu server.  I also tried manually downloading the extension with no luck.  is there an ETA on a fix or a workaround we can use to get this working in the meantime?

**Comment by Mause** [comment]
> hi there, having issues with this as well - prevents me from using duckdb on arm64 ubuntu server.  I also tried manually downloading the extension with no luck.  is there an ETA on a fix or a workaround we can use to get this working in the meantime?

For now, building it yourself is the best option. Trying to build cross distro compatible aarch64 binaries without access to a aarch64 build runner is easier said than done

**Comment by matthewmturner** [comment]
Ok got it - is it just the extension that needs to be built?  Is it fine to leave my pip installed duckdb as is?

**Comment by matthewmturner** [comment]
And would you be able to point me to any relevant docs / build script I could reference?

**Comment by Mause** [comment]
> Ok got it - is it just the extension that needs to be built?  Is it fine to leave my pip installed duckdb as is?

That's correct yeah

The build docs live here: https://duckdb.org/dev/building

**Comment by sacundim** [comment]
I just ran into this issue too. I'm using the `python:3.11-slim` Docker base image just like @tadpol.

**Comment by martelli** [comment]
Same for the issue on the M2.
The solution so far has been to rebuild with HTTPFS as a built-in and install our own package. Trying to build the module only and manually load it caused various symbol error.

**Comment by StanOswald** [comment]
Also ran into this issue when trying to fetch Spatial extension for an arm64 Mac:
```
HTTP Error: Failed to download extension "spatial" at URL "http://extensions.duckdb.org/v0.8.1/linux_arm64_gcc4/spatial.duckdb_extension.gz"
```

From the [Extensions](https://duckdb.org/docs/archive/0.8.1/extensions/overview) page, it seems that the supported platforms list doesn't include `linux_arm64_gcc4` but only `linux_arm64`.

Seems that action's setup for manylinux2014 intentionally using gcc4.8 [here](https://github.com/duckdb/duckdb/blob/a8b72b20c8a7261549145c53448dc46abbd5a54e/.github/actions/manylinux_2014_setup/action.yml). Considering this, should the wheel building process for manylinux be updated to use a newer version of g++? This would avoid appending the gcc4 postfix as described in [this](https://github.com/duckdb/duckdb/blob/a8b72b20c8a7261549145c53448dc46abbd5a54e/src/function/table/version/pragma_version.cpp) file:
```
#if !defined(_GLIBCXX_USE_CXX11_ABI) || _GLIBCXX_USE_CXX11_ABI == 0
	if (os == "linux") {
		postfix = "_gcc4";
	}
#endif
```

**Comment by Mause** [comment]
> Also ran into this issue when trying to fetch Spatial extension for an arm64 Mac:
> ```
> HTTP Error: Failed to download extension "spatial" at URL "http://extensions.duckdb.org/v0.8.1/linux_arm64_gcc4/spatial.duckdb_extension.gz"
> ```
> 
> From the [Extensions](https://duckdb.org/docs/archive/0.8.1/extensions/overview) page, it seems that the supported platforms list doesn't include `linux_arm64_gcc4` but only `linux_arm64`.
> 
> Seems that action's setup for manylinux2014 intentionally using gcc4.8 [here](https://github.com/duckdb/duckdb/blob/a8b72b20c8a7261549145c53448dc46abbd5a54e/.github/actions/manylinux_2014_setup/action.yml). Considering this, should the wheel building process for manylinux be updated to use a newer version of gcc? This would avoid appending the gcc4 postfix as described in [this](https://github.com/duckdb/duckdb/blob/a8b72b20c8a7261549145c53448dc46abbd5a54e/src/function/table/version/pragma_version.cpp) file:
> ```
> #if !defined(_GLIBCXX_USE_CXX11_ABI) || _GLIBCXX_USE_CXX11_ABI == 0
> 	if (os == "linux") {
> 		postfix = "_gcc4";
> 	}
> #endif
> ```

Manylinux is a standard ABI defined by the Python packaging authority, not something we define ourselves

**Comment by Mause** [comment]
@stanoswald I thought about your comment for a while longer, and realized we could probably update the manylinux standard version we compile for to also update the version of gcc4 we use. While this will fix this issue, it will also mean dropping support for some very old Linux versions, so we're going to test it out first before we commit

In summary, thanks for the comment!

**Comment by stanoswald** [comment]
> @stanoswald I thought about your comment for a while longer, and realized we could probably update the manylinux standard version we compile for to also update the version of gcc we use. While this will fix this issue, it will also mean dropping support for some very old Linux versions, so we're going to test it out first before we commit
> 
> In summary, thanks for the comment!

Thanks for your consideration. I hope this goes well!

**Comment by Mause** [comment]
Unfortunately the fix I made had to be pulled from the release as it caused further ABI issues

**Comment by tboddyspargo** [comment]
Sorry to hear that, @Mause; thank you for circling back.  Do you have a sense for what options or next steps we have for this issue?

**Comment by avyfain** [comment]
For those of you looking for a potential patch while the issue is resolved in the main line, an option to consider is to build duckdb yourself when you build your docker images.

I've tested that the code below works, though it did take 10+ minutes to build on my M1 mac:

```dockerfile
FROM public.ecr.aws/lambda/python:3.11

# Install pip and other dependencies
RUN pip3 install --upgrade pip \
    && yum install gcc gcc-c++ git -y

RUN git clone --depth 1 --branch v0.9.0 https://github.com/duckdb/duckdb
ENV BUILD_PYTHON=1
ENV GEN=ninja
RUN cd duckdb/tools/pythonpkg && python setup.py install

ENV HOME=/home/aws

RUN mkdir /home/aws && python3 -c "import duckdb; duckdb.query('INSTALL httpfs;');"
```

**Comment by Mause** [comment]
> For those of you looking for a potential patch while the issue is resolved in the main line, an option to consider is to build duckdb yourself when you build your docker images.
> 
> I've tested that the code below works, though it did take 10+ minutes to build on my M1 mac:
> 
> ```dockerfile
> FROM public.ecr.aws/lambda/python:3.11
> 
> # Install pip and other dependencies
> RUN pip3 install --upgrade pip \
>     && yum install gcc gcc-c++ git -y
> 
> RUN git clone --depth 1 --branch v0.9.0 https://github.com/duckdb/duckdb
> ENV BUILD_PYTHON=1
> ENV GEN=ninja
> RUN cd duckdb/tools/pythonpkg && python setup.py install
> 
> ENV HOME=/home/aws
> 
> RUN mkdir /home/aws && python3 -c "import duckdb; duckdb.query('INSTALL httpfs;');"
> ```

You can also just run `pip install duckdb --no-binary duckdb` to build from the source distribution (no need to clone manually, etc)

**Comment by tboddyspargo** [comment]
I'm now trying to work around this by building the extensions separately, using:

```sh
GEN=ninja BUILD_HTTPFS=1 BUILD_JSON=1 make release
```

Which files from the build output are required and where do they need to be placed so that `duckdb` can find them at runtime and skip the remote extension download step?

**Comment by Mytherin** [comment]
You can find the extensions in the `build` directory, e.g.:

```bash
$ > find build -name "*.duckdb_extension"
build/release/extension/autocomplete/autocomplete.duckdb_extension
build/release/extension/sqlsmith/sqlsmith.duckdb_extension
build/release/extension/inet/inet.duckdb_extension
build/release/extension/json/json.duckdb_extension
build/release/extension/tpcds/tpcds.duckdb_extension
build/release/extension/tpch/tpch.duckdb_extension
build/release/extension/parquet/parquet.duckdb_extension
build/release/extension/icu/icu.duckdb_extension
build/release/test/extension/loadable_extension_demo.duckdb_extension
build/release/test/extension/loadable_extension_optimizer_demo.duckdb_extension
```

DuckDB can install from a local path, so you can run the SQL query `INSTALL 'build/release/extension/icu/icu.duckdb_extension'` to install an extension.

**Comment by tboddyspargo** [comment]
Thank you, @Mytherin! That should suffice for a short-term workaround. 

I wonder if you or @Mause could shed some light on what the path forward for a longer-term fix might be and how feasible it is in the next release or patch of duckdb? Having pre-built, published versions of all official extensions that are installable on the basic `linux_arm64` container (resulting from below command) would provide a smoother entry ramp for developers.

Here's what my team would really love to "just work" on an Apple Silicon machine:
```sh
docker run -it --rm --entrypoint bash python:3.8-slim -c 'pip install -qq duckdb==0.9.0 && python -c "import duckdb; duckdb.connect().sql(\"INSTALL httpfs\");"'
```

**Comment by dylanpbacon** [comment]
I can confirm that I'm running into these issues as well and that having a sense of the timelines or priorities here would help plot out things on my end too regarding whether it'd be more prudent to wait or to continue to iterate on on the self-build process.

**Comment by tboddyspargo** [comment]
Thanks for the update, @Mause. I've subscribed to this issue to make sure I here about updates for GitHub provided linux/arm64 runners: https://github.com/actions/runner-images/issues/5631.

Would you consider trying one of these options in the meantime?
- https://buildjet.com/for-github-actions
- https://github.com/uraimo/run-on-arch-action

**Comment by ashpreetbedi** [comment]
Facing this issue too, anyone found a workaround?

**Comment by martelli** [comment]
I had to rebuild it from the sources and distribute myself the whl file.

**Comment by ashpreetbedi** [comment]
@martelli would it be possible to share the steps? I tried `cd duckdb/tools/pythonpkg && python setup.py install` and the `make release` but didnt get it to work.

**Comment by dchimeno** [comment]
Still facing this with 0.9.2

**Comment by ashpreetbedi** [comment]
For those that want a ready to use image, I just pushed `phidata/duckdb:0.9.2` built from source.

Run it using:
```
 docker run -it --pull always phidata/duckdb:0.9.2
```

**Comment by szarnyasg** [comment]
Hello everyone,

This thread has been quite frequently commented on in the last few months.

To clarify the status of the `linux_arm64_gcc4` extensions, I added the following line to the [working with extensions](https://duckdb.org/docs/extensions/working_with_extensions#platforms) page:
> We currently do not distribute binaries for extensions on the `linux_arm64_gcc4` platform.

The rationale behind this is that distributing these packages would require a complex CI setup that's difficult to maintain and likely incurs a large cost to run. Extensions can still be built manually for this platform.

Gabor

**Comment by dchimeno** [comment]
Given the solution leaves us (those who develop/deploy on arm under docker) without full support...

```dockerfile

FROM python:3.11-slim AS compile-image
ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    git \
    g++ \
    cmake \
    libssl-dev 

RUN python -m venv /opt/venv

# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

# duckdb
# we need to compile duckdb ourselves because duckdb doesnt provide
# binary extensions for 'httpfs' in platform: linux_arm64_gcc4
# this means duckdb is not working to query remote files in 
# both Mac M1 (only under docker) and Linux ARM (only under docker)
# Note: without docker, duckdb extensions autoload mechanism works.
# More info at:
# https://github.com/duckdb/duckdb/issues/8035

RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM"

RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
    git clone --depth 1 --branch v0.9.2 https://github.com/duckdb/duckdb && \
    cd duckdb/tools/pythonpkg && BUILD_HTTPFS=1 python -m pip install . ; \
    elif [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
    pip install duckdb==0.9.2; \
fi


FROM python:3.11-slim AS build-image
COPY --from=compile-image /opt/venv /opt/venv


# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

CMD ["python", "-c", "import duckdb;print(duckdb.sql('select count(*) from read_csv_auto(\"https://raw.githubusercontent.com/duckdb/duckdb/main/data/csv/aws_locations.csv\")'))"]
```

hope this helps.

**Comment by acirtep** [comment]
Following  https://github.com/duckdb/duckdb/issues/8035#issuecomment-1833331284, the sqlite_scanner extension works by building the extension and installing duckdb from that build:

```
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
    git clone https://github.com/duckdb/sqlite_scanner.git && \
    cd sqlite_scanner && \
    git clone --branch v0.9.2 https://github.com/duckdb/duckdb && \
    make && \
    pip uninstall -y duckdb && \
    cd duckdb/tools/pythonpkg && python -m pip install . ; \
fi
```

In order to use the extension with Python I had to create the connection with config={"allow_unsigned_extensions": "true"} and load the extension created under the above directory (sqlite_scanner/build/release/extension/sqlite_scanner/sqlite_scanner.duckdb_extension).

@faridgt you might need something similar for postgres_scanner.

**Comment by faridgt** [comment]
> RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
>     git clone https://github.com/duckdb/sqlite_scanner.git && \
>     cd sqlite_scanner && \
>     git clone --branch v0.9.2 https://github.com/duckdb/duckdb && \
>     make && \
>     pip uninstall -y duckdb && \
>     cd duckdb/tools/pythonpkg && python -m pip install . ; \
> fi

I am following those instructions but have one little issue related to postgres extension 
/postgres_scanner/src/include/postgres_utils.hpp:12:10: fatal error: libpq-fe.h: No such file or directory
I installed libq but still not resolved
apt-get install libpq-dev

**Comment by blabaschin** [comment]
For what it's worth, I still see this error. Python 3.11.3, duckdb==0.9.2. Arm, ec2 c6g. OS Ubuntu 22.0.4.
![Screenshot 2024-01-08 at 14 31 21](https://github.com/duckdb/duckdb/assets/96552924/2bca6259-d6f0-4db6-bf14-b9bae97eac58)

**Comment by jasonpang** [comment]
What didn't work for me was running a custom build of the `httpfs` extension with the pre-distributed `duckdb` Python package: 
   - I got an `Invalid ELF header` when building from macOS and copying to use on Docker
   - When building on Docker, I got undefined symbol _Zxyz errors, and Segmentation fault errors

What worked was building `duckdb` with `httpfs` together, and installing the built `duckdb` package:

### Snippet

Adding this snippet to our `Dockerfile` based on Debian `python:3.11` worked:

```Dockerfile
ARG TARGETPLATFORM
ARG BUILDPLATFORM

RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
    # On Docker on Mac M1, build DuckDB with httpfs extension and install our build of DuckDB
    apt-get update && \
    apt-get install -y g++ git cmake ninja-build libssl-dev && \
    git clone --depth 1 --branch v0.9.2 https://github.com/duckdb/duckdb && \
    cd duckdb/tools/pythonpkg && \
    export BUILD_PYTHON=1 && \
    export BUILD_HTTPFS=1 && \
    export GEN=ninja && \
    # If your project already has duckdb installed, uninstall it first
    pip uninstall duckdb -y ; \
    # Install our custom build
    pip install . ; \
fi
```

### Minimally Working Dockerfile

This was helpful getting from a minimally working example up to customizing our Dockerfile:

```Dockerfile
FROM python:3.11

RUN pip3 install --upgrade pip
RUN apt-get update && apt-get install -y g++ git cmake ninja-build libssl-dev

RUN git clone --depth 1 --branch v0.9.2 https://github.com/duckdb/duckdb
ENV BUILD_PYTHON=1
ENV BUILD_HTTPFS=1
ENV GEN=ninja

RUN cd duckdb/tools/pythonpkg && python setup.py install

# Run forever so we can run debug commands in Docker Dashboard's Exec tab
ENTRYPOINT ["tail", "-f", "/dev/null"]
```

You can then go on the Docker dashboard, go to the Exec tab, and play around with some commands:

```bash
# In the Docker exec tab
python
```

Now, in the Python environment:

```python
# In the Python shell in the Docker exec tab
import duckdb

con = duckdb.connect()
# There should be no error loading httpfs
con.load_extension("httpfs")
# Any example CSV file with an HTTPS URL will work for testing
con.execute("SELECT count(*) FROM 'https://media.githubusercontent.com/media/datablist/sample-csv-files/c2a8fe171a28b797f8df493a65be1299f1857ad7/files/people/people-100.csv';")
```

### Notes

- For some helpful example commands and tips for messing with Python and building things from source, the [DuckDB README has some good info](https://github.com/duckdb/duckdb/blob/f27e90e1d97c6d053b6864e677bb1b94caead4dd/tools/pythonpkg/README.md#installing-locally-for-development)
- I needed to set `BUILD_HTTPFS=1` to build the `httpfs` extension and also `BUILD_PYTHON=1`

**Comment by AdarshNamala** [comment]
I was facing the same issue loading  httpfs extension on an ec2 instance with aarch64.
A coiled.io  support engineer suggested installing duckdb using mamba/conda as a workaround.
I can confirm that "mamba install python-duckdb" resolved this issue for me. 
Hope this helps.

**Comment by normaljosh** [comment]
With duckdb v0.10.0, I'm facing the invalid ELF header issue on linux_amd64_gcc4

**Comment by tarasyarema** [comment]
Same as @normaljosh, having the following issue with a `duckdb.duckdb.IOException: IO Error: Extension` error with the details

```
"/path/.duckdb/extensions/v0.10.0/linux_amd64_gcc4/httpfs.duckdb_extension" could not be loaded because its signature is either missing or invalid and unsigned extensions are disabled by configuration (allow_unsigned_extensions)
```

**Comment by carlopi** [comment]
Can you do (once) `FORCE INSTALL httpfs;` and retry?

**Comment by tarasyarema** [comment]
I managed to mitigate setting the `connect(config={"allow_unsigned_extensions": "true"})` before the comment, but probably the proposed `FORCE` might be better to disable checking extensions.

Also, note that in my case it failed while running `pytest` but with local development it worked just fine. So that's something I'm gonna monitor if I find again.

In any case, @carlopi do you have an idea on why we are seeing this error? I imagine it could be related to the release being just yesterday?

**Comment by Mytherin** [comment]
We had some issues with extension uploads during the release causing (temporarily) invalid/unsigned extensions to have been uploaded yesterday. They have since been updated with working variants, but the broken version might still exist on your computer. `FORCE INSTALL httpfs` (or any extension) redownloads the file even if the extension is already installed, and hence should (hopefully) fix the problem.

**Comment by normaljosh** [comment]
@Mytherin this resolved the issue, appreciate the quick response!

**Comment by blackrez** [comment]
This is very sad to not support linux_arm64_gcc4, it is impossible to use duckdb with rust on aws lambda...If someone have an idea...

**Comment by Birne94** [comment]
> This is very sad to not support linux_arm64_gcc4, it is impossible to use duckdb with rust on aws lambda...If someone have an idea...

While not using aws lambda, with version 0.10.0 I was able to get duckdb running on sagemaker with graviton instances, so I think the amd64 builds are working now.

**Comment by sacundim** [comment]
> > This is very sad to not support linux_arm64_gcc4, it is impossible to use duckdb with rust on aws lambda...If someone have an idea...
> 
> While not using aws lambda, with version 0.10.0 I was able to get duckdb running on sagemaker with graviton instances, so I think the amd64 builds are working now.

I'm subscribed to this ticket and got confused by all this hubbub from people facing problems, so I did the Docker-based reproduction steps at the top of the ticket (and expanded a bit on them) and I see it working just fine:

```
% docker pull python:3.11-slim                  
3.11-slim: Pulling from library/python
f546e941f15b: Pull complete 
24935aba99a7: Pull complete 
07b3e0dc751a: Pull complete 
7e0115596a7a: Pull complete 
a66610a3b2a1: Pull complete 
Digest: sha256:ce81dc539f0aedc9114cae640f8352fad83d37461c24a3615b01f081d0c0583a
Status: Downloaded newer image for python:3.11-slim
docker.io/library/python:3.11-slim

% docker run -it --rm python:3.11-slim /bin/bash
root@85e22fab99d7:/# pip install duckdb
Collecting duckdb
  Downloading duckdb-0.10.0-cp311-cp311-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl.metadata (763 bytes)
Downloading duckdb-0.10.0-cp311-cp311-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 42.8 MB/s eta 0:00:00
Installing collected packages: duckdb
Successfully installed duckdb-0.10.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

root@85e22fab99d7:/# python
Python 3.11.8 (main, Feb 13 2024, 09:14:01) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import duckdb

>>> duckdb.query("install 'httpfs';")

>>> duckdb.query("load 'httpfs';")

>>> duckdb.query("select count(*) from 'https://gist.githubusercontent.com/sacundim/73bd069669edaca11e21b9f25aaa5309/raw/ba13a5065c559709476ed05eed66fd19f3b3842e/titanic_casualties.csv';")
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│           11 │
└──────────────┘
```

The `python:3.11-slim` image is currently based on Debian 12 (Bookworm); you may get different results on other operating systems, but that's down to those OSes.

Also I don't know anything about Rust, but this ticket was very clearly filed to cover the DuckDB Python extension, which is a completely different matter than the Rust API.

**Comment by tboddyspargo** [comment]
I, too, have noticed that I don't get errors trying to install extensions from a `linux/arm64` docker container running on a Silicon Mac (with `duckdb==0.10.0`)! Very exciting!

> To clarify the status of the `linux_arm64_gcc4` extensions, I added the following line to the [working with extensions](https://duckdb.org/docs/extensions/working_with_extensions#platforms) page:
> 
> > We currently do not distribute binaries for extensions on the `linux_arm64_gcc4` platform.

@Mytherin, @Mause, @szarnyasg - Did https://github.com/duckdb/duckdb/pull/10137 essentially introduce extension support for the `linux_arm64_gcc4` platform? Should we expect those binaries to continue to be made available for future releases? Should this change be reflected in the [working with extensions](https://duckdb.org/docs/extensions/working_with_extensions#platforms) page?

Thanks in advance!

**Comment by szarnyasg** [comment]
Hi @tboddyspargo, thanks for the suggestion, indeed ARM64 Linux platforms now work (thanks to moving to a newer version of the `manylinux` image in CI). We updated the extensions page at https://duckdb.org/docs/extensions/working_with_extensions#platforms

**Comment by blackrez** [comment]
Hello guys, I'm still have issue on arm64_gcc4, the extensions are still missing from the repo. Is it normal ? Or we have to wait the next release of duckdb. 

(For information, it will get a lot simpler to use duckdb with rust and lambda if extensions will be built with arm64_gcc4).

**Comment by normaljosh** [comment]
> We had some issues with extension uploads during the release causing (temporarily) invalid/unsigned extensions to have been uploaded yesterday. They have since been updated with working variants, but the broken version might still exist on your computer. `FORCE INSTALL httpfs` (or any extension) redownloads the file even if the extension is already installed, and hence should (hopefully) fix the problem.

@Mytherin I'm experiencing the same issue  invalid ELF header issue with duckdb v0.10.1 on linux_amd64_gcc4 . Could the same issues with unsigned extensions be happening on this release?

**Comment by Mytherin** [comment]
That is not expected. Could you expand on what steps you are taking to run into this issue? An invalid ELF header signifies the extensions are build for a different architecture than the machine you are running on. If that happens when using a normal `INSTALL/LOAD` workflow then perhaps something has gone wrong with publishing the release.

**Comment by normaljosh** [comment]
We operate behind a proxy, so I'm not able to run "INSTALL httpfs;" directly, instead I download the extension from http://extensions.duckdb.org/v0.10.1/linux_amd64_gcc4/httpfs.duckdb_extension.gz and send it to our server. 

Then I run this code: 
```python
import duckdb
duckdb_httpfs_path = "/path/to/httpfs.duckdb_extension.gz"
db = duckdb.connect(config={"allow_unsigned_extensions": "true"})
db.execute(f"LOAD '{duckdb_httpfs_path}';")
````
This method has worked with previous extensions on linux_amd64_gcc4, but this time I am getting the error

IOException: IO Error: Extension "/path/to/httpfs.duckdb_extension.gz" could not be loaded: /path/to/httpfs.duckdb_extension.gz: invalid ELF header

I actually still have the invalid extension that came out with the v0.10.0 release since we had to re-download it after the fix on 2/14, and it gives the same error message when I try to load that one.

**Comment by Mytherin** [comment]
Could you share the output of this command run on the server:

```py
import duckdb
duckdb.sql('PRAGMA platform')
```

**Comment by normaljosh** [comment]
┌──────────────────┐
│     platform     │
│     varchar      │
├──────────────────┤
│ linux_amd64_gcc4 │
└──────────────────┘

**Comment by Mytherin** [comment]
Ah, I think I see the problem. You need to remove gzip from the extension before loading (`gzip -d httpfs.duckdb_extension.gz`).

You should also not need to run with `allow_unsigned_extensions` when using official extensions in the first place, since they are correctly signed. In this case that is just enabling you to load an incorrectly formatted binary, which is why the ELF header error appears.

**Comment by normaljosh** [comment]
Thanks! Another team member downloaded the file and was not able to replicate the issue, so it may have been user error on my part, apologies!

**Comment by erik-farmer** [comment]
Is there a previous working version that supported `linux_arm64_gcc4`? I swear I had duckdb working with httpfs and querying S3 from my local machine that didn't require an involved setup.

For context I'm using an M1 Mac Studio and working within a docker image

**Comment by erik-farmer** [comment]
> > > This is very sad to not support linux_arm64_gcc4, it is impossible to use duckdb with rust on aws lambda...If someone have an idea...
> > 
> > 
> > While not using aws lambda, with version 0.10.0 I was able to get duckdb running on sagemaker with graviton instances, so I think the amd64 builds are working now.
> 
> I'm subscribed to this ticket and got confused by all this hubbub from people facing problems, so I did the Docker-based reproduction steps at the top of the ticket (and expanded a bit on them) and I see it working just fine:
> 
> ```
> % docker pull python:3.11-slim                  
> 3.11-slim: Pulling from library/python
> f546e941f15b: Pull complete 
> 24935aba99a7: Pull complete 
> 07b3e0dc751a: Pull complete 
> 7e0115596a7a: Pull complete 
> a66610a3b2a1: Pull complete 
> Digest: sha256:ce81dc539f0aedc9114cae640f8352fad83d37461c24a3615b01f081d0c0583a
> Status: Downloaded newer image for python:3.11-slim
> docker.io/library/python:3.11-slim
> 
> % docker run -it --rm python:3.11-slim /bin/bash
> root@85e22fab99d7:/# pip install duckdb
> Collecting duckdb
>   Downloading duckdb-0.10.0-cp311-cp311-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl.metadata (763 bytes)
> Downloading duckdb-0.10.0-cp311-cp311-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl (16.4 MB)
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 42.8 MB/s eta 0:00:00
> Installing collected packages: duckdb
> Successfully installed duckdb-0.10.0
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> 
> root@85e22fab99d7:/# python
> Python 3.11.8 (main, Feb 13 2024, 09:14:01) [GCC 12.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> >>> import duckdb
> 
> >>> duckdb.query("install 'httpfs';")
> 
> >>> duckdb.query("load 'httpfs';")
> 
> >>> duckdb.query("select count(*) from 'https://gist.githubusercontent.com/sacundim/73bd069669edaca11e21b9f25aaa5309/raw/ba13a5065c559709476ed05eed66fd19f3b3842e/titanic_casualties.csv';")
> ┌──────────────┐
> │ count_star() │
> │    int64     │
> ├──────────────┤
> │           11 │
> └──────────────┘
> ```
> 
> The `python:3.11-slim` image is currently based on Debian 12 (Bookworm); you may get different results on other operating systems, but that's down to those OSes.
> 
> Also I don't know anything about Rust, but this ticket was very clearly filed to cover the DuckDB Python extension, which is a completely different matter than the Rust API.

The hubbub in this ticket is focused on the availability of `linux_arm64_gcc4` extensions. Your example platform is `linux_arm64` and other people are citing fixes for `linux_amd64_gcc4` which makes this all the more confusing 😅

**Comment by balck3py** [comment]
I also encountered this issue in the Windows 10 environment. By following the error message
 'IO Error: Failed to download extension "postgres_scanner" at URL "http://extensions.duckdb.org/v0.10.2/windows_amd64/postgres_scanner.duckdb_extension.gz" Extension "postgres_scanner" is an existing extension.', 
Then I downloaded the gz file from the address provided in the error message, extracted it, and copied it to the local directory to resolve the issue. For the extraction directory on different operating systems, please refer to: 'https://duckdb.org/docs/extensions/overview#installation-location'. I hope the maintainers can thoroughly resolve such issues. 

Best wishes.
