### ISSUE TITLE
JOIN using explicit table function calls causes Binder Error: Duplicate alias "%s" in query!

### ISSUE THREAD

**Issue by code1704** [duckdb/duckdb#8800]
### What happens?

Using `JOIN` clause with two tables specified with explicit table function calls causes `Binder Error: Duplicate alias "%s" in query!`. For example:
```sql
select * from parquet_scan('t1.parquet')
left join parquet_scan('t2.parquet')
using (key)
```
will cause `Binder Error: Duplicate alias "parquet_scan" in query!`
However, it's okay if we simply write:
```sql
select * from 't1.parquet'
left join 't2.parquet'
using (key)
 ```

### To Reproduce

```python
import pandas as pd
import duckdb

df = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3', 'K4', 'K5'],
                    'A': ['A0', 'A1', 'A2', 'A3', 'A4', 'A5']})

other = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                      'B': ['B0', 'B1', 'B2']})

df.to_parquet('t1.parquet')
other.to_parquet('t2.parquet')

# okay
df = duckdb.query("""
    select * from 't1.parquet'
    left join 't2.parquet'
    using (key)
""").df()
print(df)

# Binder Error: Duplicate alias "parquet_scan" in query!
df = duckdb.query("""
    select * from parquet_scan('t1.parquet')
    left join parquet_scan('t2.parquet')
    using (key)
""").df()
print(df)
```

### OS:

Linux

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

mark

### Affiliation:

bq

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
This should already be fixed by https://github.com/duckdb/duckdb/pull/8170

**Comment by code1704** [comment]
@Tishj Thanks for replying. I've seen that issue upon googling this problem. But it's not exactly the same although both are triggered by the `JOIN` clause. Anyway, the problem seems to be the `alias` was mistakenly set (or not be overridden)

<img width="908" alt="image" src="https://github.com/duckdb/duckdb/assets/110730540/90ca5845-7f0f-4fd2-b011-e9e0b5d8808a"> 
<img width="922" alt="WeChatWorkScreenshot_db91117e-2195-45a8-9b44-cfd90d4c1c0c" src="https://github.com/duckdb/duckdb/assets/110730540/5dce675f-ad69-4749-b568-21b8f91c3970">

**Comment by Tishj** [comment]
Hmm I see, so this is just an issue in core, not the python client

**Comment by Bernolt** [comment]
Hi, From this thread it seems the issue have been identified but not resolved.
Could a core developer confirm?
