### ISSUE TITLE
"httpfs could not be loaded" error

### ISSUE THREAD

**Issue by kweinert** [duckdb/duckdb#9112]
### What happens?

I am trying to directly read JSON from the internet into a duckdb using R. For this, I want to use the httpfs and json extensions. However, when I use the code below with the CRAN version of duckdb (0.8.1-3), I get an error 
"Error: IO Error: Extension "C:\Users\karsten.w\AppData\Roaming\R\data\R\duckdb\.duckdb\extensions\v0.8.1\windows_amd64_rtools\httpfs.duckdb_extension" could not be loaded: Das angegebene Modul wurde nicht gefunden."
The last sentence is German and translates to: the module was not found.

(I also tried the development version 0.9 using 
`install.packages('duckdb', repos=c('https://duckdb.r-universe.dev', 'https://cloud.r-project.org')). `
Then I get a different error: "HTTP Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/v0.9.0/windows_amd64_rtools/httpfs.duckdb_extension.gz" with the hint that maybe the extensions are not uploaded (yet).

### To Reproduce
```
library(duckdb)
library(DBI)
con <- dbConnect(duckdb::duckdb(), ":memory:")
stmt <- paste(
    "INSTALL httpfs; LOAD httpfs;",
    "INSTALL json;",
    "LOAD json;",
    "select * from read_json_auto('https://openalex.s3.amazonaws.com/data/authors/updated_date%3D2023-07-21/part_000.gz', format='newline_delimited', compression='gzip') limit 100;"
)
x <- dbGetQuery(con, stmt)
```

### OS:

windows 10 x64

### DuckDB Version:

0.8.1-3

### DuckDB Client:

R

### Full Name:

Karsten Weinert

### Affiliation:

Prognos AG

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I'm confused, you state version `0.8.1-3`
Just today we released 0.9.0

**Comment by kweinert** [comment]
Hello, I updated my question to be precise. I tried the CRAN version which seems to be still 0.8.1-3 and the version from duckdb.r-universe.dev (0.9). Each version produces a different error given my code.

**Comment by tboddyspargo** [comment]
I get this error on linux arm64 (docker container) using the `duckdb==0.9.0` python package:

```
HTTPException('HTTP Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/v0.9.0/linux_arm64_gcc4/httpfs.duckdb_extension.gz"\nExtension "httpfs" is an existing extension.\n\nAre you using a development build? In this case, extensions might not (yet) be uploaded.')
```

Is there a specific timeline on which they are published relative to each release or is there some other way for us to anticipate know when they become available?

Given that #8035 was resolved via #8770, I was surprised to see that duckdb was looking for the extension in `linux_arm64_gcc4`. I had understood that it...

> effectively drops the _gcc4 postfix, enabling compatibility with our standard linux_arm64 platform extension builds.
> -- https://github.com/duckdb/duckdb/pull/8770#issue-1878708428

Thanks in advance for your responses, we've been very excited about the release of 0.9.0!

**Comment by Mause** [comment]
Unfortunately the fix for #8035 had to be pulled as it didn't fix things, and only caused further ABI issues

**Comment by szarnyasg** [comment]
This works now. 

> Is there a specific timeline on which they are published relative to each release or is there some other way for us to anticipate know when they become available?

The extensions are published by the CI, which starts right when the release is tagged. Unless there is a failure in the CI job, the extensions should be available a few hours after the release.
